### ISSUE TITLE
Add additional highcharts modules

### ISSUE THREAD

**Issue by asteinhart** [chicagomaroon/data-visualizations#53]
Add source modules to `index.html` template: 
* `https://code.highcharts.com/11.0.0/highcharts-more.js` for bubble chart and other features
*  `https://code.highcharts.com/11.0.0/modules/data.js` for importing data from csv or googlesheet into highcharts

**Comment by michplunkett** [comment]
Would you like to take a shot at adding this to the repository, or would you prefer otherwise?
